CREATE DEFINER=`root`@`localhost` FUNCTION `fn_generar_nombre`(p_genero VARCHAR(1)) RETURNS varchar(60) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
    RETURN CASE
        WHEN p_genero='H' THEN ELT(FLOOR(1+RAND()*100),
		'Juan','Carlos','Miguel','Luis','José',
		'Jorge','Pedro','Andrés','Daniel','Fernando',
		'Ricardo','Manuel','Alejandro','Francisco','David',
		'Diego','Antonio','Jesús','Raúl','Sergio',
		'Roberto','Alberto','Mario','Héctor','Adrián',
		'Gabriel','Martín','Esteban','Óscar','Rodrigo',
		'Enrique','Pablo','Emilio','Iván','Jaime',
		'Guillermo','Salvador','Ramón','Ángel','Hugo',
		'Leonardo','Rafael','Gustavo','Cristian','Sebastián',
		'Brayan','Kevin','Axel','Samuel','Isaac',
		'Matías','Benjamín','Emanuel','Tomás','Fabián',
		'Elías','Lucas','Nicolás','Álvaro','Jonathan',
		'Edgar','Marco','Julio','César','Mauricio',
		'Felipe','Cristóbal','Gerardo','Israel','Víctor',
		'Ernesto','Rubén','Noé','Simón','Bruno',
		'Gael','Damián','Maximiliano','Ian','Emiliano',
		'Joel','Omar','Saúl','Lorenzo','Agustín',
		'Valentín','Renato','Alan','Armando','Claudio',
		'Vicente','Patricio','Adolfo','Ismael','Efraín')

        WHEN p_genero='M' THEN ELT(FLOOR(1+RAND()*100),
		'María','Ana','Lucía','Sofía','Fernanda',
		'Valeria','Camila','Daniela','Elena','Paola',
		'Andrea','Ximena','Gabriela','Victoria','Isabella',
		'Renata','Natalia','Carolina','Alejandra','Mariana',
		'Patricia','Rosa','Claudia','Laura','Verónica',
		'Adriana','Mónica','Sandra','Liliana','Diana',
		'Lorena','Karla','Alejandrina','Carmen','Gloria',
		'Rocío','Teresa','Beatriz','Luz','Emilia',
		'Regina','Julia','Julieta','Montserrat','Vanessa',
		'Yuliana','Esmeralda','Brenda','Tatiana','Melissa',
		'Dayana','Bianca','Ángela','Noelia','Ariana',
		'Valentina','Martina','Antonella','Emma','Allison',
		'Naomi','Miranda','Paulina','Daniela','Sara',
		'Abigail','Jimena','Alondra','Fátima','Catalina',
		'Michelle','Zoe','Bárbara','Yamileth','Leslie',
		'Samara','Giselle','Karen','Cecilia','Itzel',
		'Mayra','Tania','Belén','Maribel','Guadalupe',
		'Elisa','Yesenia','Nadia','Silvia','Carla',
		'Frida','Ingrid','Alicia','Estefanía','Araceli')

        ELSE ELT(FLOOR(1+RAND()*100),
		'Alexis','Avery','Bailey','Blake','Cameron',
		'Casey','Dakota','Drew','Elliot','Harley',
		'Jamie','Jesse','Kai','Kendall','Logan',
		'Parker','Quinn','Reese','Riley','Rowan',
		'Skyler','Spencer','Tristan','Adrianne','Ainsley',
		'Alma','Amaris','Amaya','Anahi','Anya',
		'Arlette','Ashley','Aspen','Aubrey','Aurora',
		'Azul','Belen','Brisa','Chantal','Chloe',
		'Crystal','Dafne','Dana','Danna','Delilah',
		'Destiny','Eileen','Elisa','Elodie','Erika',
		'Evelin','Fiona','Genesis','Gina','Grecia',
		'Hanna','Hayley','Iliana','Indira','Irene',
		'Jade','Janeth','Jazmin','Jennifer','Jessica',
		'Joanna','Joselyn','Judith','Kiara','Kimberly',
		'Karla','Larissa','Leidy','Lia','Linda',
		'Lisbeth','Lizbeth','Mabel','Madeleine','Magdalena',
		'Mara','Maritza','Melany','Mia','Mireya',
		'Nayeli','Nicole','Nubia','Olga','Pamela',
		'Raquel','Ruth','Salma','Sheila','Sindy')
    END;
END